name: build
on:
  pull_request:
    branches: ['master']
  push:
    branches: ['master']
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:

      matrix:
        version: ['1.6', '1.7', '1.8', '1.9', '1.10']
        os:  [windows-latest, ubuntu-latest, macOS-12, macOS-14]
        arch:
          - x64
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-runtest@latest
